[package]
name = "connect"
version = "0.1.2"
edition = "2021"
authors = ["Sweta Rohit <swetar@mechasystems.com"]
description = "Client application for the Mecha Agent"
documentation = "https://docs.mecha.so"
license = "MIT"
repository = "https://github.com/mecha-org/mecha-agent"
homepage = "https://mecha.so"

[[bin]]
name = "mecha-connect"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = { version = "0.7.0-beta.1", features=["libadwaita"] }
relm4-macros = "0.7.0-beta.1"
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive",] }
serde_yaml = "0.9.21"
image = "0.24.7"
tonic = "0.9.2"
prost = "0.11.9"
async-trait = "0.1.73"
tokio = {version = "1.35.1", features = ["full"] }
tokio-util = "0.7.10"
reqwest = "0.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
init-tracing-opentelemetry = { version = "0.12.0", features = ["otlp", "tracing_subscriber_ext"] }
opentelemetry-appender-tracing = "0.2.0"
simple-base64 = "0.23.2"

[build-dependencies]
tonic-build = "0.9.2"

[package.metadata.deb]
name = "connect"
depends = "$auto"
assets = [
    # binary
    [
        "../../target/release/mecha-connect",
        "/usr/bin/",
        "755",
    ],
    # desktop file
    [
        "./src/packaging/linux/org.mecha.connect.desktop", 
        "/usr/share/applications/", 
        "644"
    ],
]
