[package]
name = "telemetry"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
events = { path = "../core/events" }
services = { path = "../core/services" }
agent_settings = { path = "../core/settings" }
messaging = { path = "../messaging" }
identity = { path = "../identity" }
anyhow = { version = "1.0.71", features = ["backtrace"]}
serde_json = "1.0.33"
serde = { version  = "1.0.159", features = ["derive"]}
tonic = "0.10.2"
tracing = "0.1"
tracing-opentelemetry-instrumentation-sdk = "0.15.0"
sentry-anyhow = { version= "0.32.1", features = ["backtrace"]}
sha256 = "1.1.2"
tokio = { version = "1.27.0", features = ["full"] }