[package]
name = "networking"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
settings = { path = "../settings" }
events = { path = "../core/events" }
messaging = { path = "../messaging" }
identity = { path = "../identity" }
anyhow = { version = "1.0.71", features = ["backtrace"]}
tokio = { version = "1.27.0" }
tonic = "0.10.2"
tracing = "0.1"
tokio-util = "0.7.10"